### ISSUE TITLE
Should we stop scraping global rank information?

### ISSUE THREAD

**Issue by saifulwebid** [jtkencode/cp-leaderboard#10]
I noticed that [the Codeforces data is frequently updated](https://github.com/jtkencode/cp-leaderboard/commits/master/data/codeforces.json). However, the changes are mostly to the `global_rank` field.

I think it is not relevant for us to store global ranks (not only in Codeforces, but in Atcoder also, for example). Global ranks will be changing frequently because people out there also improve their ranks.

I believe we are interested more in the progress of Encode members themselves, but this is only my assumption - what do you think guys @imamfzn @mughieams @fauh45?

(Creating this issue as a future history that we've considered this. Now I'll wait for asynchronous feedback for 24 hours. If I heard nothing after that, I'll remove the field by myself. 😂)

**Comment by saifulwebid** [comment]
Had a quick chat in Telegram with @imamfzn.

<img width="525" alt="image" src="https://user-images.githubusercontent.com/1644410/96362988-8e2de280-115b-11eb-95a8-269825084686.png">

**Comment by imamfzn** [comment]
I still don't get your point. Why don't we just store that information and treat it like a meta data ? even though we don't need yet.

**Comment by imamfzn** [comment]
> I noticed that [the Codeforces data is frequently updated](https://github.com/jtkencode/cp-leaderboard/commits/master/data/codeforces.json). However, **the changes** are mostly to the `global_rank` field.
> 

Totally aggree if the concern is a not relevant git commit changes :sweat_smile:

**Comment by saifulwebid** [comment]
I think we never discuss on why we're storing them in Git commits 😂 

My idea is to track someone's development on online judges. If our scraper create a Git commit, I would assume someone made a progress.

Storing `polban_rank` I think still relevant. For example, in a Git commit, `polban_rank` for `A` changed, but her score didn't change at that commit. It's still fine, because a change in `polban_rank` in that commit means that on the same commit, someone's `polban_rank` also changed, and her score should've changed too.

But storing `global_rank` is not too relevant, as someone's `global_rank` may change without doing anything, and also without all Encode members doing anything.

What do you think? @imamfzn

**Comment by imamfzn** [comment]
yup, let's remove the `global_rank` @saifulwebid
